---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  labels:
    app: simple-httpd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simple-httpd
      
  template:
    metadata:
      labels:
        app: simple-httpd
        tier: simple-httpd
    spec:
      containers:
        - name: simple-httpd
          image: IMAGE_PATH
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: simple-httpd
...

---
apiVersion: v1
kind: Service
metadata:
  name: simple-httpd-service
  labels:
    app: simple-httpd-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: simple-httpd
    tier: simple-httpd
  type: LoadBalancer
  ...